<a href="https://colab.research.google.com/github/Andreslop26/math/blob/main/practicas/practica_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Práctica 3. Álgebra
* Para aprender sobre Python vea la playlist [Python para Matemáticas](https://www.youtube.com/playlist?list=PL8gpDXwO-9l4HkDJ9QhB4H-cOiT0BYGau)
* Para obtener ideas y vídeos para la resolución de la práctica vea los archivos siguientes: [Ideas](https://github.com/financieras/math/tree/main/ideas)

## Práctica 3.1
**Determinante en Excel**  

* Cree un fichero en Excel de nombre algebra.xlsm.
* La extensión **xlsm** corresponde a los archivos de Excel habilitados para macros.
* Utilice la Hoja 1 para hacer la Práctica 3.1.
* Se pide:
 1. Cree una matriz cuadrada de dimensión 5×5, formada por números aleatorios enteros entre -9 y +9.
 2. Calcule el determinante de esta matriz
 3. Cree un programa en **VBA** que busque una matriz de este tipo cuyo determinante sea cero.
 4. Copie la matriz encontrada y péguela debajo con "pegado especial valores" para que no varíe su contenido al efectuar el recálculo manual de la hoja.

## Práctica 3.2
**Matriz inversa en Excel**  

* Use el mismo archivo de Excel con extensión **xlsm** del caso anterior. 
* Utilice la Hoja 2 para hacer la Práctica 3.2.
* Se pide:
 1. Crea la matriz $A$ que es una matriz cuadrada de dimensiones 5×5 usando números aleatorios enteros entre -9 y +9, excepto cero
 2. Calcule su determinante
 3. Calcule su transpuesta usando la función ```TRANSPONER```
 4. Calcule su matriz inversa $A^{-1}$
 5. Multiplique la matriz $A$ por su inversa $A^{-1}$ y compruebe que el producto es la matriz identidad.
 $$AA^{-1}=I$$

## Práctica 3.3
**Resolución de sistemas lineales en Excel**  

* Use el mismo archivo de Excel con extensión **xlsm** del caso anterior. 
* Utilice la Hoja 3 para hacer la Práctica 3.3.
* Se pide:
 1. Cree un sistema de 5 ecuaciones con 5 incógnitas con **solución única**.
 2. Una de las ecuaciones será: $\quad x_1+2x_2-x_3+x_4-3x_5=6$
 3. Muestre las ecuaciones del sistema usando el [editor de ecuaciones](https://support.microsoft.com/es-es/office/editor-de-ecuaciones-6eac7d71-3c74-437b-80d3-c7dea24fdf3f) de Excel. $\quad Ax=b$
 4. Monte la matriz $A$ del sistema de ecuaciones y la matriz $b$ con los términos independientes. Muestre ambas matrices.
 5. Calcule la matriz inversa $A^{-1}$
 6. Resuelva el sistema lineal de ecuaciones con este método: $\quad Ax=b \quad \Longrightarrow \quad x=A^{-1}b$
 7. Compruebe si el resultado obtenido es la solución del sistema de ecuaciones. Justifique esa comprobación.

## Práctica 3.4
**Matriz inversa en Python**  

Desarrolla un código en Python que al ejecutarse consiga los siguientes apartados.  
1. Crea una matriz cuadrada de dimensiones 3×3 usando números aleatorios enteros entre -9 y +9, excepto cero
2. Buscar un caso donde el determinante sea igual a 1
3. Si el determinante es 1 imprime la matriz y su determinante
4. Calcula e imprime su transpuesta
5. Calcula e imprime su matriz inversa
6. Multiplica la matriz creada por su inversa y comprueba que el producto es la matriz identidad.
7. Calcula cuantos segundos ha tardado en realizarse el proceso.

In [3]:
from random import randint
print(randint(-9, 9))

8


In [4]:
import random

contador = 0
valor_deseado = 42

while True:
    rnd = random.choice(list(range(1000)))
    contador += 1   # contador = contador + 1
    if rnd == valor_deseado:
        print(f"Se han realizado {contador} ciclos en el bucle hasta encontrar el valor deseado.")
        break

print("Fin del programa")
     

Se han realizado 1363 ciclos en el bucle hasta encontrar el valor deaseado.
Fin del programa


In [12]:
from random import randint, seed
seed()
m = []
for i in range(5):
    fila = []
    for j in range(5):
        fila.append(randint(0,9))
    m.append(fila)

m 

import numpy as np

lista = [1,2,3,4]
vector = np.array(lista)   # convertimos la matriz en un ndarray
print(vector)
print(lista)

import numpy as np
m = [[1,-2,3], [4,5,6], [7,8,0]]
np.linalg.det(m)


import numpy as np
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matriz:")
print(m)
print("\nTasnpuesta:")
print(np.transpose(m))

import numpy as np

m = np.array([[1,-7, -8], [ 1,-4,-4], [-1,3,3]])
print("Matriz:")
print(m)
print()

print("Inversa:")
minv = np.linalg.inv(m)
print(minv)
print()

print("Matriz Identidad:")
identidad = np.dot(m, minv)   # multiplicación de matrices
print(identidad)
print()

print("Matriz Identidad con valores enteros:")
print(identidad.astype(int))   # así forzamos a valores enteros



import numpy as np

a = np.random.randint(0, 6, size=(3,3))
b = np.random.randint(0, 6, size=(3,3))

print(a)
print()

print(b)
print()

print(np.dot(a, b))    # Método 1 para multiplicar matrices
print()

print(np.matmul(a,b))  # Método 2 para multiplicar matrices
print()

print(a @ b)           # Método 3 para multiplicar matrices
print()

print(a*b)             # Cuidado!!! esto no es el producto matricial
     
     

[1 2 3 4]
[1, 2, 3, 4]
Matriz:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Tasnpuesta:
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Matriz:
[[ 1 -7 -8]
 [ 1 -4 -4]
 [-1  3  3]]

Inversa:
[[ 0. -3. -4.]
 [ 1. -5. -4.]
 [-1.  4.  3.]]

Matriz Identidad:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Matriz Identidad con valores enteros:
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[3 4 4]
 [0 0 1]
 [2 4 3]]

[[0 5 2]
 [5 1 2]
 [0 5 5]]

[[20 39 34]
 [ 0  5  5]
 [20 29 27]]

[[20 39 34]
 [ 0  5  5]
 [20 29 27]]

[[20 39 34]
 [ 0  5  5]
 [20 29 27]]

[[ 0 20  8]
 [ 0  0  2]
 [ 0 20 15]]


## Práctica 3.5
**Resolución de sistemas lineales en Python**  

1. Cree un sistema de 4 ecuaciones con 4 incógnitas con **solución única**.
2. La solución del sistema es: $\; \begin{pmatrix}x_1, x_2, x_3, x_4\end{pmatrix} = \begin{pmatrix} 3, 4, 5, 2\end{pmatrix}$  
3. Una de las ecuaciones del sistema es: $\enspace x_1+3x_2-x_3-2x_4=6$  
4. El vector $b$ de términos independientes es: $\enspace b=\begin{pmatrix}6, 3, 5, 7\end{pmatrix}$  
5. Usando números aleatorios elija los coeficientes que faltan de la matriz $A$ del sistema de ecuaciones.
  - Los coeficientes deben ser números enteros entre -5 y +5, excluido el cero.
  - Imprima la matriz $A$.  
6. Calcule e imprima el determinante de $A$.
7. Calcule e imprima la matriz inversa $A^{-1}$  
8. Resuelva el sistema lineal de ecuaciones con este método: $$Ax=b \quad \Longrightarrow \quad x=A^{-1}b$$
9. Compruebe que el resultado obtenido es la solución del sistema de ecuaciones.  
10. Resuelva nuevamente el sistema de ecuaciones usando ```np.linalg.solve```.

In [16]:
import numpy as np
np.random.choice([0,1,2,3,4,5,6,7,8,9], 3)

list(range(-9,0)) + list(range(1,10))


import numpy as np

v = np.array([1,2,4,3])   # vector conocido, supongamos que es la solución de sistema lineal

def busca(b):
    while True:
        w = np.random.choice(list(range(-5,0)) + list(range(1,6)), 4)
        if np.matmul(v, w) == b:   # el producto de los dos vectores debe ser igual al número b
            break
    return w

b =  5; print(f"{busca(b)} x {v} = {b}")
b = -3; print(f"{busca(b)} x {v} = {b}")
b = -1; print(f"{busca(b)} x {v} = {b}")
b = -2; print(f"{busca(b)} x {v} = {b}")

# Multiplicando a mano el primer vector sería un vector fila y
# el segundo un vector columna
# Al usar NumPy no nos preocupamos de la congruendia de vector



import numpy as np

f1 = [-4, -2, 4,  2]
f2 = [-5,  2,  4, -5]
f3 = [-5, 5, -3,  4]
f4 = [2,  2, -1, -5]
matriz = [f1, f2, f3, f4]
print(matriz)
print()

# m es un ndarray (n dimensional array)
m = np.array(matriz)
m
     
import numpy as np
a = np.array([[2,-1,2], [3,2,-1], [4,3,-3]])
b = np.array([6,4,1])
a_inv = np.linalg.inv(a)
np.dot(a_inv, b)
     

[-2  5 -3  3] x [1 2 4 3] = 5
[ 1 -1  1 -2] x [1 2 4 3] = -3
[-5  5 -3  2] x [1 2 4 3] = -1
[ 2  2  1 -4] x [1 2 4 3] = -2
[[-4, -2, 4, 2], [-5, 2, 4, -5], [-5, 5, -3, 4], [2, 2, -1, -5]]



array([1., 2., 3.])

## Práctica 3.6
**Resolución de sistemas lineales con Octave**  

1. Tome el mismo sistema 4x4 con solución única del ejercicio anterior.
2. Muestra el sistema usando $\LaTeX$
3. Resuélvelo con Octave por dos métodos
4. ¿Ambos métodos dan el mismo resultado?

## Práctica 3.7
**Diagonalización en Python**

* Sea la matriz cuadrada $A$ de orden 4x4

$$A=\left(
\begin{array}{rrrr}
 -1 &-2 &  3 &-1 \\
  0 & 2 &  0 & 0 \\
  0 & 0 &  2 & 0 \\
  0 & 0 &  0 & 1
\end{array}
\right)$$
1. Calcula los **autovalores** y **autovectores**
2. Calcula y muestra:
 - la matriz diagonal $D$
 - la matriz de paso $P$
 - su inversa $P^{-1}$  
3. Comprueba que se cumple que $A^3=PD^3P^{-1}$

In [25]:
from sympy import Matrix
A = Matrix([[-3,2,0,0], [-3,4,0,0], [0,0,-5,-4], [0,0,-2,2]])
P, D = A.diagonalize()
D
   

Matrix([
[-6,  0, 0, 0],
[ 0, -2, 0, 0],
[ 0,  0, 3, 0],
[ 0,  0, 0, 3]])

In [26]:
P

Matrix([
[0, 2, 1,  0],
[0, 1, 3,  0],
[4, 0, 0, -1],
[1, 0, 0,  2]])

In [27]:
import numpy as np
A = np.array([[-3,2,0,0], [-3,4,0,0], [0,0,-5,-4], [0,0,-2,2]])
print(A@A@A)

[[ -15   14    0    0]
 [ -21   34    0    0]
 [   0    0 -189 -108]
 [   0    0  -54    0]]


In [28]:
import numpy as np
A = np.array([[-3,2,0,0], [-3,4,0,0], [0,0,-5,-4], [0,0,-2,2]])
d,P = np.linalg.eig(A)
print("d: ", d)
D = np.diag(d)
print("\nD:\n", D)
print("\nP:\n", P)
Dcubo = D @ D @ D
print("\nDcubo:\n", Dcubo)
print("\nSolución:\n", P @ Dcubo @ np.linalg.inv(P))

d:  [-2.  3. -6.  3.]

D:
 [[-2.  0.  0.  0.]
 [ 0.  3.  0.  0.]
 [ 0.  0. -6.  0.]
 [ 0.  0.  0.  3.]]

P:
 [[-0.89442719 -0.31622777  0.          0.        ]
 [-0.4472136  -0.9486833   0.          0.        ]
 [ 0.          0.         -0.9701425   0.4472136 ]
 [ 0.          0.         -0.24253563 -0.89442719]]

Dcubo:
 [[  -8.    0.    0.    0.]
 [   0.   27.    0.    0.]
 [   0.    0. -216.    0.]
 [   0.    0.    0.   27.]]

Solución:
 [[-1.50000000e+01  1.40000000e+01  0.00000000e+00  0.00000000e+00]
 [-2.10000000e+01  3.40000000e+01  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.89000000e+02 -1.08000000e+02]
 [ 0.00000000e+00  0.00000000e+00 -5.40000000e+01 -2.74319149e-15]]


## Práctica 3.8
**Diagonalización con Octave**

Resuelva el ejercicio anterior, pero en esta ocasión utilizando Octave.

In [11]:
# La instalación puede tardar algo más de un minuto
!apt update
!apt install octave
     



Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:3 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:5 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/ InRelease
Hit:6 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic InRelease
Hit:7 http://ppa.launchpad.net/cran/libgit2/ubuntu bionic InRelease
Ign:8 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Hit:9 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
Hit:10 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu bionic InRelease
Hit:11 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release
Hit:12 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu bionic InRelease
Reading package lists... Done
Building dependency tree       
Reading state infor

## Práctica 3.9
**Libertad para elegir el lugar de trabajo**  
Resolver con **Octave**.

Una empresa de 1.000 empleados permite que sus trabajadores cada día acudan a trabajar a la oficina o que realicen su trabajo desde su casa. Inicialmente el 90% de la plantilla trabajaba en la oficina y solo el 10% lo hacían en casa. Se ha observado que los que un día trabajan en casa tienen una probabilidad del 70% de realizarlo también desde casa al día siguiente, pero que en el restante 30% de los casos acuden a la oficina al día siguiente. Por el contrario, se ha observado que los que un día trabajaron en la oficina al día siguiente vuelven
a la oficina en el 60% de los casos y en el 40% restante van a su casa al día siguiente.
* Determinar qué número de empleados se quedan en casa transcurridos dos días.
* ¿Y a largo plazo cuantos se quedan en casa?

## Práctica 3.10
**Tendencia del mercado**  
Resolver con **Python**.

En el mercado de automóviles de gran lujo únicamente se disputan la clientela dos marcas (A y B). Las ventas son $M=100.000$ automóviles anuales, no variando esta cifra con el transcurso de los años. La marca A es líder de mercado en este momento con el 75% de las ventas. Sus directivos desean consolidar su liderazgo e incluso aumentarlo, para lo cual todos los años efectúan una fuerte campaña publicitaria con la que consiguen cada año un 40% de los que fueron clientes de su competidora, aunque la empresa A pierde un 20% de sus clientes que se van a la competencia.
* ¿Cuál es la situación a los 3 años?
* ¿Y al cabo de mucho tiempo?

In [19]:
import numpy as np

X0 = np.array([.75, .25])
A = np.array([[.8, .4], [.2 ,.6]])
X3 = A@A@A@X0
print("Situación a los tres años:", X3)

d,P = np.linalg.eig(A)
D = np.diag(d)
Pinv = np.linalg.inv(P)
A10 = P@(D**10)@Pinv
X10 = A10@X0
print("Situación a los diez años:", X10)
print("Situación a los veinte años:", P@(D**20)@Pinv@X0)

Situación a los tres años: [0.672 0.328]
Situación a los diez años: [0.6666754 0.3333246]
Situación a los veinte años: [0.66666667 0.33333333]


In [20]:
# A cubo
A@A@A

array([[0.688, 0.624],
       [0.312, 0.376]])

In [21]:
# comprobación de que esta expresión es igual a A cubo
P@(D**3)@Pinv

array([[0.688, 0.624],
       [0.312, 0.376]])

In [22]:
A@A@A@A@A@A@A@A@A@A

array([[0.66670162, 0.66659676],
       [0.33329838, 0.33340324]])

In [23]:
P@(D**10)@Pinv

array([[0.66670162, 0.66659676],
       [0.33329838, 0.33340324]])

In [24]:
np.round(A@A@A@A@A@A@A@A@A@A, 12) == np.round(P@(D**10)@Pinv, 12)

array([[ True,  True],
       [ True,  True]])